### ISSUE TITLE
API/Usage documentation

### ISSUE THREAD

**Issue by bmarcio20** [Nikhilkoneru/react-d3-zoomable-sunburst#1]
Is it possible to add an API or Usage documentation on the readme files?

**Comment by Nikhilkoneru** [comment]
Sure I'll add it today.

**Comment by bmarcio20** [comment]
Thanks for your response. I really want to use the module, but I don't seem to find the right way to use it or to pass data correctly. I formatted data same as the d3 documentations asks for sunburst ({name: string, children: array}) but I always get a circular 100% pie chart.

**Comment by Nikhilkoneru** [comment]
@bmarcio20 updated this package to v1.0.5. To see the usage look at the example code in the example folder.
Git clone this repository
cd example
npm run start

**Comment by marcio-b** [comment]
Great man! it was a lot of help! thank you very much! Please feel free to close this issue =)
