### ISSUE TITLE
When use onSelect the tooltipContent stay visible

### ISSUE THREAD

**Issue by adrienbecuwe** [Nikhilkoneru/react-d3-zoomable-sunburst#2]
when i add the props onSlect the tooltip but and stay visible after click..
morr you click nore you will see old tooltip visible

```

const [currentSelection, setCurrentSelection] = useState(0);
  const onSelect = (event) => {
      setCurrentSelection(event.data)
 }

      <Sunburst
          data={dataTest}
          scale={scale}
          tooltipContent={ <div class="sunburstTooltip" style="position:absolute; color:'#000000'; z-index:10; background: #FFFFFF; padding: 5px; text-align: center;" /> }
          tooltip
          keyId="Sunburst"
          width={width * 0.8}
          value={'size'}
          height={height * 0.8}
          onSelect={onSelect}
      />
  
```

![Screenshot 2020-10-14 at 14 59 07](https://user-images.githubusercontent.com/2499562/95992312-1e072000-0e2e-11eb-8686-cd4ed19fc781.png)

![Screenshot 2020-10-14 at 14 59 58](https://user-images.githubusercontent.com/2499562/95992288-16477b80-0e2e-11eb-80b6-89ba5707364f.png)
![Screenshot 2020-10-14 at 14 59 51](https://user-images.githubusercontent.com/2499562/95992298-1a739900-0e2e-11eb-8cdb-ba82f0382fa4.png)

**Comment by Nikhilkoneru** [comment]
Hi Adrien Becuwe, will check and update this package tonight if it is necessary

**Comment by Nikhilkoneru** [comment]
Hi Adrien Becuwe, it is working perfectly in the example which I provided in this repository, can you reverify your issue?.

**Comment by adrienbecuwe** [comment]
Hi,
if follow the example all works well.
the problem is when i use onSelect.

**Comment by adrinoe** [comment]
Hi,

for fix this issue you need to change the click  line 60 to

`function click(d) { // eslint-disable-line
                node = d; // eslint-disable-line
                props.onSelect && props.onSelect(d);
                svg.selectAll('path').transition().duration(1000).attrTween('d', arcTweenZoom(d));
                if (props.tooltip) {
                    d3.select(this).style('cursor', 'default');
                    tooltip.transition().duration(50).style('opacity', 0);
                }
  }`

Thanks
Adrien
